### ISSUE TITLE
Not longer working

### ISSUE THREAD

**Issue by godhandkiller** [docterd/MusaicFM#23]
I've been using this screen saver for a couple of months and I haven't had any issues

But starting today is not longer workin, when I go to the options the button is disabled and can't click on it. I try to reinstall it but without success

![Screen Shot 2020-01-17 at 11 28 19](https://user-images.githubusercontent.com/18409311/72645618-ab6a2200-3939-11ea-83a2-c431b16d9cbf.png)

**Comment by godhandkiller** [comment]
Ok after much try and error I had to uninstall and install it again manually and that worked.

**Comment by docterd** [comment]
This issue got resolved in https://github.com/docterd/MusaicFM/issues/20

**Comment by jeremymeyers** [comment]
This is still happening for me, even after removing and re-adding on 10.15.6
